# This is a basic workflow to help you get started with Actions

name: Build and Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # gets the google test submodule
      - name: Checkout submodules
        run: git submodule update --init --recursive
      #creates the output directory for our build
      - name: Generate output Directory
        run: mkdir cmake-build-debug
      # build the project
      - name: build with cmake
        run: ./buildWithCMake.sh
      #test the project using google test and cmake
      - name: Test Project
        run: cd cmake-build-debug && ctest
